/**
 * Auto-generated TypeScript types for nestjs-i18n-client
 *
 * This file is automatically generated by the module on initialization.
 * Do not edit manually.
 *
 * If you see this file with the fallback type, it means types haven't been
 * generated yet. Types will be generated automatically when the module initializes.
 */

// Fallback type - will be replaced when types are generated
export type TranslationKey = string;

// Module augmentation for nestjs-i18n
// This extends the I18nService.t() method with type-safe autocomplete
declare module 'nestjs-i18n' {
  interface I18nService {
    /**
     * Translate a key with type-safe autocomplete
     * @param key - Translation key (autocomplete supported)
     * @param options - Translation options
     */
    t(key: TranslationKey, options?: any): string;
  }
}
