#!/usr/bin/env node
/**
 * Type generator script for nestjs-i18n-client
 * Fetches translation keys from API and generates TypeScript type definitions
 */

import axios, { AxiosInstance } from 'axios';
import * as fs from 'fs';
import * as path from 'path';

interface GenerateTypesOptions {
  apiUrl: string;
  apiKey: string;
  category?: string;
  defaultLanguage?: string;
  outputPath?: string;
}

// Extract all keys from nested translation object
function extractKeys(obj: Record<string, any>, prefix = ''): string[] {
  const keys: string[] = [];

  for (const [key, value] of Object.entries(obj)) {
    const fullKey = prefix ? `${prefix}.${key}` : key;

    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      // Recursively extract keys from nested objects
      keys.push(...extractKeys(value, fullKey));
    } else {
      // Leaf node - this is a translation key
      keys.push(fullKey);
    }
  }

  return keys;
}

// Convert keys to TypeScript union type
function generateTypeDefinition(keys: string[]): string {
  if (keys.length === 0) {
    return `export type TranslationKey = string;`;
  }

  // Sort keys for better readability
  const sortedKeys = [...keys].sort();

  // Generate union type
  const typeDefinition = sortedKeys.map((key) => `  | '${key}'`).join('\n');

  return `export type TranslationKey =
${typeDefinition};
`;
}

// Generate module augmentation for nestjs-i18n
function generateModuleAugmentation(): string {
  return `
// Module augmentation for nestjs-i18n I18nService
// This extends the I18nService.t() method with type-safe autocomplete
declare module 'nestjs-i18n' {
  interface I18nService {
    /**
     * Translate a key with type-safe autocomplete
     * @param key - Translation key (autocomplete supported)
     * @param options - Translation options
     */
    t(key: import('./types').TranslationKey, options?: any): string;
  }
}
`;
}

// Fetch translations from API
async function fetchTranslations(
  httpClient: AxiosInstance,
  language: string,
  category: string
): Promise<Record<string, any>> {
  try {
    const response = await httpClient.get(
      `/translations?category=${category}&language=${language}`
    );

    if (!response.data.success) {
      throw new Error('API returned unsuccessful response');
    }

    return response.data.data || {};
  } catch (error: any) {
    throw new Error(
      `Failed to fetch translations: ${error.message || 'Unknown error'}`
    );
  }
}

// Main function
async function generateTypes(options: GenerateTypesOptions): Promise<void> {
  const {
    apiUrl,
    apiKey,
    category = 'web',
    defaultLanguage = 'en',
    outputPath = path.join(__dirname, '..', 'dist', 'types.d.ts'),
  } = options;

  console.log('🔍 Fetching translations from API...');
  console.log(`   API URL: ${apiUrl}`);
  console.log(`   Category: ${category}`);
  console.log(`   Language: ${defaultLanguage}`);

  // Create HTTP client
  const httpClient = axios.create({
    baseURL: apiUrl,
    timeout: 30000,
    headers: {
      'x-api-key': apiKey,
      'Content-Type': 'application/json',
    },
  });

  try {
    // Fetch translations
    const translations = await fetchTranslations(
      httpClient,
      defaultLanguage,
      category
    );

    // Extract all keys
    const keys = extractKeys(translations);
    console.log(`✅ Found ${keys.length} translation keys`);

    if (keys.length === 0) {
      console.warn('⚠️  No translation keys found. Generating fallback type.');
    }

    // Generate type definition
    const typeDefinition = generateTypeDefinition(keys);
    const moduleAugmentation = generateModuleAugmentation();

    // Combine into final file content
    const fileContent = `/**
 * Auto-generated TypeScript types for nestjs-i18n-client
 * 
 * This file is automatically generated. Do not edit manually.
 * Last generated: ${new Date().toISOString()}
 */

${typeDefinition}
${moduleAugmentation}
`;

    // Ensure output directory exists
    const outputDir = path.dirname(outputPath);
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    // Write file
    fs.writeFileSync(outputPath, fileContent, 'utf-8');
    console.log(`✅ Types generated successfully: ${outputPath}`);
  } catch (error: any) {
    console.error('❌ Failed to generate types:', error.message);
    process.exit(1);
  }
}

// CLI interface
if (require.main === module) {
  const args = process.argv.slice(2);
  const options: GenerateTypesOptions = {
    apiUrl: '',
    apiKey: '',
  };

  // Parse command line arguments
  for (let i = 0; i < args.length; i += 2) {
    const key = args[i];
    const value = args[i + 1];

    switch (key) {
      case '--api-url':
        options.apiUrl = value;
        break;
      case '--api-key':
        options.apiKey = value;
        break;
      case '--category':
        options.category = value;
        break;
      case '--language':
        options.defaultLanguage = value;
        break;
      case '--output':
        options.outputPath = value;
        break;
    }
  }

  // Validate required options
  if (!options.apiUrl || !options.apiKey) {
    console.error('❌ Missing required options: --api-url and --api-key');
    console.error('');
    console.error('Usage:');
    console.error(
      '  generate-types --api-url <url> --api-key <key> [--category <category>] [--language <lang>] [--output <path>]'
    );
    process.exit(1);
  }

  generateTypes(options).catch((error) => {
    console.error('❌ Error:', error.message);
    process.exit(1);
  });
}

export { generateTypes, GenerateTypesOptions };
